# Generated by Django 4.2.7 on 2025-08-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_percentage', models.FloatField(default=50.0)),
                ('acceleration_percentage', models.FloatField(default=50.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Robot Settings',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
