# Generated by Django 3.1.12 on 2025-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motion_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
