# Generated by Django 4.2.23 on 2025-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("joint1", models.FloatField()),
                ("joint2", models.FloatField()),
                ("joint3", models.FloatField()),
                ("joint4", models.FloatField()),
                ("joint5", models.FloatField()),
                ("joint6", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="ButtonLog",
        ),
    ]
