# Generated by Django 4.2.23 on 2025-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_robotlog_delete_buttonlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("APP_ERROR", "Application Error"),
                            ("ROBOT_ERROR", "Robot Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
