# Generated by Django 4.2.23 on 2025-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_systemevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="robotlog",
            name="total_angle",
            field=models.FloatField(default=0.0),
        ),
    ]
