# Generated by Django 4.2.23 on 2025-07-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_robotlog_total_angle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="robotlog",
            name="total_angle",
        ),
    ]
