# Generated by Django 4.2.23 on 2025-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_remove_robotlog_total_angle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("HARDWARE", "Hardware"), ("SOFTWARE", "Software")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
