# Generated by Django 3.2.25 on 2025-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedRobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('joint1', models.FloatField(blank=True, null=True)),
                ('joint2', models.FloatField(blank=True, null=True)),
                ('joint3', models.FloatField(blank=True, null=True)),
                ('joint4', models.FloatField(blank=True, null=True)),
                ('joint5', models.FloatField(blank=True, null=True)),
                ('joint6', models.FloatField(blank=True, null=True)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('acceleration', models.FloatField(blank=True, null=True)),
                ('gripper', models.FloatField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
